describe('Login Test Case', () => {
    it('Login with valid credentials', () => {
        cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login').as('loginRequest1')
        cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
        cy.get('input[name="username"]').type('Admin')
        cy.get('input[name="password"]').type('admin123')
        cy.get('button[type="submit"]').click()
        cy.wait('@loginRequest1').its('response.statusCode').should('eq', 200)
        cy.url().should('include', '/dashboard')
        cy.get('.oxd-topbar-header-breadcrumb > .oxd-text').should('contain', 'Dashboard')
    })
    it('fails with invalid credentials', () => {
        cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login').as('loginRequest2')
        cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
        cy.get('input[name="username"]').type('InvalidUser')
        cy.get('input[name="password"]').type('InvalidPass')
        cy.get('button[type="submit"]').click()
        cy.wait('@loginRequest2').its('response.statusCode').should('eq', 200)
        cy.get('.oxd-alert-content').should('contain', 'Invalid credentials')
    })
    it('fails with empty credentials', () => {
        cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login').as('loginRequest3')
        cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
        cy.get('button[type="submit"]').click()
        cy.wait('@loginRequest3').its('response.statusCode').should('eq', 200)
        cy.get('.oxd-text.oxd-text--span.oxd-input-field-error-message.oxd-input-group__message').should('contain', 'Required')
    })
    it('fails with empty username', () => {
        cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login').as('loginRequest4')
        cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
        cy.get('input[name="password"]').type('admin123')
        cy.get('button[type="submit"]').click()
        cy.wait('@loginRequest4').its('response.statusCode').should('eq', 200)
        cy.get('.oxd-text.oxd-text--span.oxd-input-field-error-message.oxd-input-group__message').should('contain', 'Required')
    })
    it('fails with empty password', () => {
        cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login').as('loginRequest5')
        cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
        cy.get('input[name="username"]').type('Admin')
        cy.get('button[type="submit"]').click()
        cy.wait('@loginRequest5').its('response.statusCode').should('eq', 200)
        cy.get('.oxd-text.oxd-text--span.oxd-input-field-error-message.oxd-input-group__message').should('contain', 'Required')
    })

})